{
  "name": "netlify-functions",
  "version": "1.0.0",
  "description": "Fonctions serverless pour GivPlus v2",
  "main": "index.js",
  "scripts": {
    "postinstall": "npm install faunadb@4.7.0 --no-save"
  },
  "dependencies": {
    "faunadb": "^4.7.0",
    "jsonwebtoken": "^8.5.1",
    "stripe": "^11.18.0"
  }
}
