[build]
  publish = "dist"
  command = "npx vite build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
